"""Training-independent corrections (verified against code / sources)."""
E = [
    # --- abstract ---
    ("We mounted an ordinary dashcam and an inexpensive MPU-6050 accelerometer (100 Hz) on city transit buses.",
     "The system is designed to run on an ordinary dashcam and an inexpensive MPU-6050 accelerometer (100 Hz) mounted on city transit buses; no bus has been instrumented yet, so images come from public road datasets and accelerometer data from real car drive logs."),
    ("an on-board edge computer processes the sensor data directly.",
     "the software is written to run on an on-board edge computer (it currently runs on a laptop-class CPU)."),
    ("estimates their real-world area and depth through calibrated camera homography,",
     "estimates their real-world area by projecting pixels onto the road plane (from an assumed camera mount unless a per-vehicle calibration profile is supplied) and their depth as an interval estimate rather than a measurement,"),
    ("checks whether the bus chassis actually felt a bump using a Bayesian sensor gate,",
     "checks, when an accelerometer window is supplied, whether the vehicle actually felt a bump using a Bayesian sensor gate,"),
    # --- building blocks ---
    ("We use camera calibration and homography to convert pixel regions into real square meters and centimeter depths.",
     "We project segmented pixels onto the road plane using the camera's height, pitch and focal length to get square metres; depth cannot be measured from one image, so it is reported as an estimate with a low-high interval."),
    ("Our system clusters detections within 8 meters using Haversine distance, confirming the defect while merging the reports into one ticket.",
     "Our system merges reports of the same defect class within 8 metres (Haversine distance), confirming the defect while merging the reports into one ticket."),
    ("To follow the DPDP Act 2023, pedestrian faces and non-offending license plates are blurred on the bus before anything is transmitted.",
     "To follow the DPDP Act 2023, a redaction step blurs the head region of every detected person and any number plate found inside detected vehicles before an image is shared (models/privacy_redactor.py); its recall has not yet been measured on an annotated set."),
    ("By adding a low-power edge computer to each bus, inspection happens passively during routine transit.",
     "Adding a low-power edge computer to each bus would make inspection passive during routine transit (proposed deployment; not yet trialled on a bus)."),
    # --- justification ---
    ("Over 5,000 fatalities and 10,000 spinal/orthopedic injuries happen every year.",
     "MoRTH recorded 5,626 pothole deaths across 2018-2020, roughly 1,900 a year."),
    ("We formulated an objective, automated Priority Index: PI = w1*(100 - PCI) + w2*Vol + w3*Traffic. This guarantees that repair budgets are spent based on real road hazard severity rather than political influence.",
     "We propose an objective Priority Index: PI = w1*(100 - PCI) + w2*Vol + w3*Traffic. It is not implemented yet and its weights are not set; the current ledger orders work by PCI-based SLA tiers (24 / 48 / 72 hours)."),
    # --- literature table ---
    ("2. Koch & Brilakis (2011) ASCE J. Comp. Civ. Eng.", "2. Koch & Brilakis (2011) Adv. Eng. Informatics"),
    ("reached 86% precision.", "reached 86% accuracy (82% precision, 86% recall) on 120 images."),
    ("3. Mednis et al. (2011) IEEE ISSNIP", "3. Mednis et al. (2011) IEEE DCOSS"),
    ("reached 78% true positive rate.", "reported true-positive rates up to 90% (Z-DIFF)."),
    ("6. Du et al. (2021) Autom. in Constr.", "6. Zhu et al. (2022) Autom. in Constr."),
    ("Dual-camera UAV aerial photogrammetry with semi-supervised YOLOv3 for highway inspection.",
     "UAV imagery with YOLO-family detectors for highway pavement distress."),
    ("High-altitude aerial inspection of highway pavements; reached 88.3% classification accuracy.",
     "Aerial inspection of highway pavements from drone imagery."),
    ("7. Bhatia et al. (2022) IEEE Access", "7. Bhatia et al. (2022) J. King Saud Univ. CIS"),
    ("Thermal infrared imaging combined with CNNs to find moisture pockets and voids beneath asphalt.",
     "Thermal images classified with CNNs to detect potholes."),
    ("Spots underground water pockets before the asphalt collapses into a pothole.",
     "Detects potholes in thermal images, which do not depend on daylight."),
    ("8. Ran et al. / Yang et al. (2024) CVPR", "8. Yang et al. (2024) NeurIPS"),
    ("12. Al-Qawasmeh et al. (2021) Sensors", "12. Anjomshoaa et al. (2018) IEEE IoT J."),
    ("Distributed sensing using municipal garbage trucks equipped with GPS receivers and cameras.",
     "City Scanner: drive-by sensing platform mounted on municipal garbage trucks."),
    ("No deduplication or audit security: databases were flooded with repeated tickets; no protection against invoice fraud.",
     "Environmental sensing platform: no defect deduplication or tamper-evident work orders."),
    ("Monocular Calibration + IRC Bands: uses single camera homography with IRC depth bands, running sub-5W on CPU.",
     "Monocular ground-plane projection + IRC depth bands: area from one calibrated camera, depth as an interval within IRC patching bands; runs on CPU (power draw not measured)."),
    ("Fixed-Mount Fleet Hardware: cameras and IMUs are rigidly bolted to the bus chassis with lane-polygon bounds.",
     "Fixed-mount fleet hardware (proposed): camera and IMU bolted to the bus, with a per-vehicle calibration profile."),
    # --- datasets table ---
    ("Severe class skew; annotated with bounding boxes rather than segmentation masks.",
     "Severe class skew; annotated with bounding boxes rather than segmentation masks; smartphone/car imagery, not bus-mounted."),
    ("390 images (700 rejected duplicates)", "1,287 files (915 pothole, 372 plain road); 700 of 739 images in one re-uploaded set rejected as pHash duplicates"),
    ("2,000 balanced images", "2,376 patches - excluded from training"),
    ("Cataloged with domain='concrete'; down-weighted in fusion to avoid confusing asphalt texture.",
     "Excluded from road-scene training and measurement by pipeline/corpus_policy.py (227x227 wall/concrete close-ups with no road geometry)."),
    ("500 high-res photos", "None - not in the corpus"),
    ("Cropped to 640x480; CLAHE adaptive contrast applied; used to benchmark alligator crack edges.",
     "No CRACK500 image is in the repository; the folder named 03_crack500_fatigue holds DNIT road photos and the excluded Kaggle concrete patches. Listed here only to correct earlier drafts."),
    ("67 curated images (14/19/20/14)", "207 images: 67 field photographs (14/19/20/14) + 140 Wikimedia Commons (35 per class)"),
    # --- preprocessing ---
    ("We calculate the Laplacian variance across the road portion of the frame. If the variance is below 42.5, the frame is flagged as non-road and skipped immediately, saving CPU power.",
     "We calculate the standard deviation of luminance over the lower 65% of the frame. If it is below 6.5 (no visible asphalt grain), the frame is flagged as non-road and skipped immediately, saving CPU power."),
    ("Calculates Laplacian variance and filters out frames that do not depict a road surface.",
     "Calculates luminance standard deviation over the road region and filters out frames that do not depict a road surface."),
    ("Using our camera height (2.45 m) and mounting pitch angle, we apply a 3x3 homography matrix H to warp perspective pixels into an orthographic bird's-eye grid, giving us true square meters of damage.",
     "Using the camera height and pitch (1.45 m / 18.4 deg assumed by default; 1.52 m / 16 deg in the one bus profile, whose intrinsics come from the lens field of view) and the focal length, every defect pixel is projected onto the flat road plane and its ground footprint summed, giving square metres of damage."),
    ("We run it through a 4th-order Butterworth bandpass filter (0.5 Hz to 25 Hz). This removes static gravity tilt and engine buzz, leaving only real road shock spikes.",
     "Each 1-second window has its per-axis mean removed (which removes gravity and mounting tilt); the RandomForest then uses FFT band energies, crest factor, skewness, kurtosis and jerk, and the 1-D CNN learns directly from the centred signal. No band-pass filter is applied."),
    ("An on-device face and plate detection pass applies a 15x15 Gaussian blur over pedestrians and nearby cars. The edge device only transmits an encrypted JSON packet under 1 KB per event, never raw video.",
     "A redaction pass blurs the head region of every detected person and any plate the contour localiser finds inside detected vehicles (Gaussian kernel of at least 15x15 px, scaled to the region). Work orders are compact JSON sealed with SHA-256, which makes them tamper-evident but not encrypted; transport encryption (TLS) belongs to the deployment and is not implemented in this prototype."),
    ("Faces and civilian license plates are blurred on the bus before any data leaves, satisfying the DPDP Act 2023.",
     "People's heads and number plates are blurred by the redaction step before an image is shared, in support of the DPDP Act 2023; detection recall has not yet been measured."),
    # --- methodology stages ---
    ("Finds candidate distress patches using spatial saliency and grid clustering.",
     "Finds candidate distress regions with an 11-feature pixel segmenter (gradient-boosted trees), whose pothole pixels are kept only where the CNN classifier also sees a pothole (semantic gate); painted markings are masked out first."),
    ("Converts candidate pixel regions into real metric area (m^2) and cavity depth (cm).",
     "Converts candidate pixel regions into ground area (m^2) by ground-plane projection, and attaches a depth estimate with a low-high interval (not a measurement)."),
    ("Extracts the matching 1.0-second tri-axial accelerometer buffer from the MPU-6050.",
     "Scores a 1.0-second tri-axial accelerometer window when one is supplied with the frame; without one, the stage reports that no IMU data was available rather than inventing it."),
    # --- justification table ---
    ("GPS receivers drift 3 to 5 meters in urban street canyons. Haversine clustering handles Earth curvature and GPS jitter, preventing multiple tickets for the same pothole.",
     "GPS receivers drift 3 to 5 meters in urban street canyons. Haversine clustering within 8 m, restricted to the same defect class, absorbs GPS jitter and prevents multiple tickets for the same pothole without merging different defects."),
    # --- plan ---
    ("Download and process RDD2022's Indian road subset (47,000 photos) to improve alligator crack and pothole diversity on local pavement textures.",
     "Extend the RDD2022 India ingestion (done in this milestone; RDD2022 has 47,420 photographs across all countries, of which the India archive is one part) with pixel-level labels for water-filled potholes."),
]
